Meta\OntologyCreateBundle\Entity\RestrictionType:
    type: entity
    table: restrictiontypes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        description:
            type: text
    #Внешние ключи
    #Связанные со мной
    oneToMany:
        restrictions:
            targetEntity: OntologyRestriction
            mappedBy: restrictiontype