Meta\OntologyCreateBundle\Entity\SimpleDataType:
    type: entity
    table: simpledatatypes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        description:
            type: text
    #Внешние ключи
    #Связанные со мной
    oneToMany:
        datatype:
            targetEntity: DataType
            mappedBy: simpledatatype
    