meta_ontology_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MetaOntologyBundle:Default:index }
MetaOntologyBundle_ontology:
        resource: "@MetaOntologyBundle/Resources/config/routing/ontology.yml"
        prefix:   /list

