services:
    meta_ontology.admin.ontology:
        class: Meta\OntologyCreateBundle\Admin\OntologyAdmin
        arguments: [~, Meta\OntologyCreateBundle\Entity\Ontology, MetaOntologyBundle:OntologyAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Ontology}
