Meta\ClassificationLegalEntitiesBundle\Entity\OwnershipForm:
    type: entity
    table: ownershipforms
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
    oneToMany:
        legalentities:
            targetEntity: LegalEntity
            mappedBy: ownershipform