list:
    pattern:  /
    defaults: { _controller: "MetaOntologyBundle:Ontology:index" }

list_show:
    pattern:  /{id}/show
    defaults: { _controller: "MetaOntologyBundle:Ontology:show" }

list_new:
    pattern:  /new
    defaults: { _controller: "MetaOntologyBundle:Ontology:new" }

list_create:
    pattern:  /create
    defaults: { _controller: "MetaOntologyBundle:Ontology:create" }
    requirements: { _method: post }

list_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MetaOntologyBundle:Ontology:edit" }

list_update:
    pattern:  /{id}/update
    defaults: { _controller: "MetaOntologyBundle:Ontology:update" }
    requirements: { _method: post|put }

list_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MetaOntologyBundle:Ontology:delete" }
    requirements: { _method: post|delete }
