ontology:
    pattern:  /
    defaults: { _controller: "MetaOntologyBundle:Ontology:index" }

ontology_show:
    pattern:  /{id}/show
    defaults: { _controller: "MetaOntologyBundle:Ontology:show" }

ontology_new:
    pattern:  /new
    defaults: { _controller: "MetaOntologyBundle:Ontology:new" }

ontology_create:
    pattern:  /create
    defaults: { _controller: "MetaOntologyBundle:Ontology:create" }
    requirements: { _method: post }

ontology_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MetaOntologyBundle:Ontology:edit" }

ontology_update:
    pattern:  /{id}/update
    defaults: { _controller: "MetaOntologyBundle:Ontology:update" }
    requirements: { _method: post|put }

ontology_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MetaOntologyBundle:Ontology:delete" }
    requirements: { _method: post|delete }
