meta_classification_legal_entities_homepage:
    pattern:  /
    defaults: { _controller: MetaClassificationLegalEntitiesBundle:Default:index }
MetaClassificationLegalEntitiesBundle_legalentity:
    resource: "@MetaClassificationLegalEntitiesBundle/Resources/config/routing/legalentity.yml"
    prefix:   /legalentity
